language: go
install:
- bash .travis-fork-fix
- go get github.com/robfig/glock
- go get -d github.com/gluster/aplo
- glock sync github.com/gluster/aplo/src/ams
- bash .travis-fork-fix
matrix:
  include:
  - go: 1.5.3
    env: OPTIONS="-race"
  - go: 1.6
    env: COVERAGE="true" OPTIONS=""
before_script:
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/cover
script:
- go fmt ./... | wc -l | grep 0
- go vet ./...
- go test -v $OPTIONS ./...
